
[mcp_servers.context7]
command = "docker"
args = ["run", "-i", "--rm", "mcp/context7"]

[mcp_servers.convex]
command = "cmd"
args = ["/c", "npx", "convex", "mcp", "start"]

[mcp_servers.Context7]
command = "docker"
args = ["run", "-i", "--rm", "mcp/context7"]

[mcp_servers.playwright]
command = "docker"
args = ["run", "-i", "--rm", "mcp/playwright"]
