default_agents = ["copilot", "augment", "claude", "windsurf", "cline", codex]

[mcp]
enabled = true
strategy = "merge" # or "overwrite"

[gitignore]
enabled = true

[agents.copilot]
enabled = true
output = ".github/copilot-instructions.md"

[agents.cursor]
enabled = true
output = ".cursor/rules/ruler_cursor_instructions.mdc"

[agents.claude]
enabled = true
output = "CLAUDE.md"
