# .github/workflows/release.yml  
name: Release
on:
  push:
    branches: [main, master]
    # Only run when version in package.json changes
    paths: ['package.json']
  # Allow manual triggering
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: false  # Enable when we're ready for automated releases
    steps:
      - uses: actions/checkout@v4
        with:
          # Need full history for changelog generation
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
        
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run quality checks
        run: |
          pnpm typecheck
          pnpm check
          pnpm repo:guards
          
      - name: Run tests
        run: |
          pnpm test:backend
          # pnpm test:web  # Enable when frontend tests exist
          
      - name: Build for production
        run: pnpm build
        
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false