# .github/workflows/test-full.yml
name: Full Test Suite
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  # Matrix testing across Node versions (when we need broader compatibility)
  test-matrix:
    name: Test Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    if: false  # Enable when we need cross-version testing
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with: { node-version: '${{ matrix.node-version }}' }
        
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-node${{ matrix.node-version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node-version }}-pnpm-
            
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run all tests
        run: |
          pnpm typecheck
          pnpm check  
          pnpm test:backend
          # pnpm test:web  # Enable when frontend tests exist

  # Integration tests (when we have them)
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    if: false  # Enable when we add integration tests
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
        
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run integration tests
        run: pnpm test:integration
        
  # E2E tests (when we have them)  
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    if: false  # Enable when we add E2E tests
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
        
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
        
      - name: Run E2E tests
        run: pnpm test:e2e
        
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30